### ISSUE TITLE
Check if the email is unique in user create method

### ISSUE THREAD

**Issue by inciotiq** [Iotiq-Erste/users-module#17]
**Feature Description**
The create and update service methods should check if the user's email is unique. 

**Requirements**
**1.** The system should not allow duplicate emails.

**Comment by foolmarshal** [comment]
Hey @inciotiq 

I was going through the project was found it really amazing and inline with my current skillsets.
Tried to solve this issue.

PR can be found at: https://github.com/Iotiq-Erste/users-module/pull/22

Kindly have a look, and let me know if I missed anything or if further improvements needed in the PR.

PS: recently started contributing to open source, so pardon for any blunders. Open to learn new stuff here.
